package vista;

import controlador.controladorPaciente;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.paciente;
import modelo.pacienteDAO;


/**
 *
 * @author INESMARIAO
 */
public class frmPacientes extends javax.swing.JFrame {

    public int idTempo;
    
 
    public frmPacientes() {
        initComponents();
        // para que la ventana aparezca en el centro de la pantalla
        this.setTitle("Pacientes");
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        controladorPaciente c=new controladorPaciente(this);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        tbpPacientes = new javax.swing.JTabbedPane();
        pnCrearPacientes = new javax.swing.JPanel();
        cbxEstadoPac = new javax.swing.JPanel();
        cbxTipoDocCrearPac = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDocumentoCrearPac = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombresCrearPac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoCrearPac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefonoCrearPac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDireccionCrearPac = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmailCrearPac = new javax.swing.JTextField();
        btnCancelarCrearPac = new javax.swing.JButton();
        btnGuardarCrearPac = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pnModificarPacientes = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbxModificarBuscarPac = new javax.swing.JComboBox<>();
        pnModificarDatosPac = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbxTipoDocModificarPac = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtDocumentoModificarPac = new javax.swing.JTextField();
        txtNombresModificarPac = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtApellidoModificarPac = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelefonoModificarPac = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDireccionModificarPac = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEmailModificarPac = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnCancelarModificarPac = new javax.swing.JButton();
        btnGuardarModificarPac = new javax.swing.JButton();
        cbxEstadoModificarPac = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        pnBuscarPacientes = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        cbxCampoaBuscarPac = new javax.swing.JComboBox<>();
        txtBuscarPaciente = new javax.swing.JTextField();
        btnBuscarPaciente = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultadoBuscarPac = new javax.swing.JTable();
        pnListarPacientes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListarPacientes = new javax.swing.JTable();
        btnActualizarListaPac = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArchivoPacientes = new javax.swing.JMenu();
        mniVentanaPpalPacientes = new javax.swing.JMenuItem();
        mniSalirPacientes = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        tbpPacientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbpPacientesFocusGained(evt);
            }
        });

        cbxEstadoPac.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nuevo Paciente"), "Nuevo Paciente"));

        cbxTipoDocCrearPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "CC", "CE" }));

        jLabel1.setText("Tipo de documento:");

        jLabel2.setText("Número documento:");

        jLabel3.setText("Nombres:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Teléfono:");

        jLabel6.setText("Dirección:");

        jLabel7.setText("Email:");

        btnCancelarCrearPac.setText("Cancelar");
        btnCancelarCrearPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCrearPacActionPerformed(evt);
            }
        });

        btnGuardarCrearPac.setText("Guardar");
        btnGuardarCrearPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCrearPacActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paciente2.jpg"))); // NOI18N

        javax.swing.GroupLayout cbxEstadoPacLayout = new javax.swing.GroupLayout(cbxEstadoPac);
        cbxEstadoPac.setLayout(cbxEstadoPacLayout);
        cbxEstadoPacLayout.setHorizontalGroup(
            cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbxEstadoPacLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cbxEstadoPacLayout.createSequentialGroup()
                        .addComponent(btnCancelarCrearPac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarCrearPac))
                    .addComponent(txtEmailCrearPac)
                    .addComponent(txtDireccionCrearPac)
                    .addComponent(txtTelefonoCrearPac)
                    .addComponent(txtApellidoCrearPac)
                    .addComponent(txtNombresCrearPac)
                    .addComponent(txtDocumentoCrearPac)
                    .addGroup(cbxEstadoPacLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbxTipoDocCrearPac, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cbxEstadoPacLayout.setVerticalGroup(
            cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbxEstadoPacLayout.createSequentialGroup()
                .addGroup(cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cbxEstadoPacLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbxTipoDocCrearPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDocumentoCrearPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombresCrearPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoCrearPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(9, 9, 9)
                        .addGroup(cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoCrearPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cbxEstadoPacLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtDireccionCrearPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailCrearPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(cbxEstadoPacLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(cbxEstadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCrearPac)
                    .addComponent(btnGuardarCrearPac))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnCrearPacientesLayout = new javax.swing.GroupLayout(pnCrearPacientes);
        pnCrearPacientes.setLayout(pnCrearPacientesLayout);
        pnCrearPacientesLayout.setHorizontalGroup(
            pnCrearPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCrearPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxEstadoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCrearPacientesLayout.setVerticalGroup(
            pnCrearPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCrearPacientesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cbxEstadoPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpPacientes.addTab("Crear", pnCrearPacientes);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Selecciona un paciente"));

        jLabel10.setText("Pacientes:");

        cbxModificarBuscarPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxModificarBuscarPac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxModificarBuscarPacItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(cbxModificarBuscarPac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbxModificarBuscarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnModificarDatosPac.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Modificar datos del paciente"));

        jLabel11.setText("Tipo de documento:");

        cbxTipoDocModificarPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "CC", "CE" }));

        jLabel12.setText("Número documento:");

        jLabel13.setText("Nombres:");

        jLabel14.setText("Apellidos:");

        jLabel15.setText("Teléfono:");

        jLabel16.setText("Dirección:");

        jLabel17.setText("Email:");

        jLabel18.setText("Estado:");

        btnCancelarModificarPac.setText("Cancelar");
        btnCancelarModificarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModificarPacActionPerformed(evt);
            }
        });

        btnGuardarModificarPac.setText("Guardar");
        btnGuardarModificarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModificarPacActionPerformed(evt);
            }
        });

        cbxEstadoModificarPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user3.png"))); // NOI18N

        javax.swing.GroupLayout pnModificarDatosPacLayout = new javax.swing.GroupLayout(pnModificarDatosPac);
        pnModificarDatosPac.setLayout(pnModificarDatosPacLayout);
        pnModificarDatosPacLayout.setHorizontalGroup(
            pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnModificarDatosPacLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(3, 3, 3)
                .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnModificarDatosPacLayout.createSequentialGroup()
                        .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmailModificarPac, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionModificarPac, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoModificarPac, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoModificarPac, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombresModificarPac, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDocumentoModificarPac, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnModificarDatosPacLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(cbxTipoDocModificarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(pnModificarDatosPacLayout.createSequentialGroup()
                        .addComponent(cbxEstadoModificarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarModificarPac)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarModificarPac)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnModificarDatosPacLayout.setVerticalGroup(
            pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnModificarDatosPacLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnModificarDatosPacLayout.createSequentialGroup()
                        .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbxTipoDocModificarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtDocumentoModificarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombresModificarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoModificarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(9, 9, 9)
                        .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoModificarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnModificarDatosPacLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(txtDireccionModificarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailModificarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(pnModificarDatosPacLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(pnModificarDatosPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxEstadoModificarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelarModificarPac)
                        .addComponent(btnGuardarModificarPac)))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout pnModificarPacientesLayout = new javax.swing.GroupLayout(pnModificarPacientes);
        pnModificarPacientes.setLayout(pnModificarPacientesLayout);
        pnModificarPacientesLayout.setHorizontalGroup(
            pnModificarPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnModificarPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnModificarPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnModificarDatosPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnModificarPacientesLayout.setVerticalGroup(
            pnModificarPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnModificarPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnModificarDatosPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpPacientes.addTab("Modificar", pnModificarPacientes);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Búsqueda de Pacientes"));

        jLabel20.setText("Campo a buscar:");

        cbxCampoaBuscarPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el campo a buscar...", "Nombres", "Apellidos", "Telefono", "No. documento" }));

        btnBuscarPaciente.setText("Buscar");
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCampoaBuscarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarPaciente)
                .addGap(39, 39, 39))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbxCampoaBuscarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPaciente))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de Pacientes:"));

        tblResultadoBuscarPac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo de Documento", "Número Documento", "Nombres", "Apellidos", "Teléfono", "Dirección", "Email", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblResultadoBuscarPac.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblResultadoBuscarPac);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnBuscarPacientesLayout = new javax.swing.GroupLayout(pnBuscarPacientes);
        pnBuscarPacientes.setLayout(pnBuscarPacientesLayout);
        pnBuscarPacientesLayout.setHorizontalGroup(
            pnBuscarPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscarPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnBuscarPacientesLayout.setVerticalGroup(
            pnBuscarPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        tbpPacientes.addTab("Buscar", pnBuscarPacientes);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pacientes"));

        tblListarPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo de Documento", "Número Documento", "Nombres", "Apellidos", "Teléfono", "Dirección", "Email", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListarPacientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(tblListarPacientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnActualizarListaPac.setText("Actualizar");

        javax.swing.GroupLayout pnListarPacientesLayout = new javax.swing.GroupLayout(pnListarPacientes);
        pnListarPacientes.setLayout(pnListarPacientesLayout);
        pnListarPacientesLayout.setHorizontalGroup(
            pnListarPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListarPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListarPacientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizarListaPac)
                .addGap(28, 28, 28))
        );
        pnListarPacientesLayout.setVerticalGroup(
            pnListarPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListarPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarListaPac)
                .addGap(23, 23, 23))
        );

        tbpPacientes.addTab("Listar", pnListarPacientes);

        mnArchivoPacientes.setText("Archivo");

        mniVentanaPpalPacientes.setText("Ventana Principal");
        mnArchivoPacientes.add(mniVentanaPpalPacientes);

        mniSalirPacientes.setText("Salir");
        mniSalirPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirPacientesActionPerformed(evt);
            }
        });
        mnArchivoPacientes.add(mniSalirPacientes);

        jMenuBar1.add(mnArchivoPacientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniSalirPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirPacientesActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniSalirPacientesActionPerformed

    private void btnCancelarCrearPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCrearPacActionPerformed
        limpiarCamposfrmCrear();
    }//GEN-LAST:event_btnCancelarCrearPacActionPerformed

    private void tbpPacientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbpPacientesFocusGained
        cargarListaPacientes(this.cbxModificarBuscarPac);
    }//GEN-LAST:event_tbpPacientesFocusGained

    private void btnGuardarCrearPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCrearPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCrearPacActionPerformed

    private void cbxModificarBuscarPacItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxModificarBuscarPacItemStateChanged
        try {
            paciente Paciente = (paciente) cbxModificarBuscarPac.getSelectedItem();
            cbxTipoDocModificarPac.setSelectedItem(Paciente.getTipoDoc().toString());
            txtDocumentoModificarPac.setText(String.valueOf(Paciente.getNumeroDocumento()));
            txtNombresModificarPac.setText(Paciente.getNombres());
            txtApellidoModificarPac.setText(Paciente.getApellidos());
            txtTelefonoModificarPac.setText(String.valueOf(Paciente.getTelefono()));
            txtDireccionModificarPac.setText(Paciente.getDireccion());
            txtEmailModificarPac.setText(Paciente.getEmail());
            cbxEstadoModificarPac.setSelectedItem(Paciente.isEstado() ? "Activo" : "Inactivo");
            this.idTempo = Paciente.getId();
            pnModificarDatosPac.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbxModificarBuscarPacItemStateChanged

    private void btnGuardarModificarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModificarPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarModificarPacActionPerformed

    private void btnCancelarModificarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModificarPacActionPerformed
       limpiarCamposfrmModificar();
    }//GEN-LAST:event_btnCancelarModificarPacActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        // TODO add your handling code here:
        String Campo = cbxCampoaBuscarPac.getSelectedItem().toString();
        String Termino = txtBuscarPaciente.getText();
        pacienteDAO daoPacie = new pacienteDAO();
        ArrayList<paciente> arrPacientes = new ArrayList<paciente>();
        arrPacientes = daoPacie.Buscar(daoPacie.formarWherePaciente(Campo, Termino));
        daoPacie.listPacientesTabla(arrPacientes, tblResultadoBuscarPac);
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

public void limpiarCamposfrmCrear(){
        cbxTipoDocCrearPac.setSelectedIndex(0);
        txtDocumentoCrearPac.setText("");
        txtNombresCrearPac.setText("");
        txtApellidoCrearPac.setText("");
        txtTelefonoCrearPac.setText("");
        txtDireccionCrearPac.setText("");
        txtEmailCrearPac.setText("");
    }

public void limpiarCamposfrmModificar(){
        cbxTipoDocModificarPac.setSelectedIndex(0);
        txtDocumentoModificarPac.setText("");
        txtNombresModificarPac.setText("");
        txtApellidoModificarPac.setText("");
        txtTelefonoModificarPac.setText("");
        txtDireccionModificarPac.setText("");
        txtEmailModificarPac.setText("");
        cbxEstadoModificarPac.setSelectedIndex(0);
    }

public static void cargarListaPacientes(JComboBox combo){
        combo.removeAllItems();
        ArrayList <paciente> listPacientes;
        pacienteDAO pacie = new pacienteDAO();
        listPacientes = pacie.Buscar("1");
        for (paciente pac : listPacientes) {
            combo.addItem(pac);
        }
    }

/*public static void cargarListaPacientes(JComboBox combo, int Id){
        combo.removeAllItems();
        ArrayList <paciente> listPacientes;
        pacienteDAO pacie = new pacienteDAO();
        listPacientes = pacie.Buscar("1");
        for (paciente daoPacie : listPacientes) {
            combo.addItem(daoPacie);
            if(daoPacie.getId() == Id){
                combo.setSelectedItem(daoPacie);
            }
        }
    }*/

private boolean validarDatos (){
        if(cbxTipoDocCrearPac.getSelectedItem().toString().isEmpty() || txtDocumentoCrearPac.getText().isEmpty() || txtNombresCrearPac.getText().isEmpty() ||  txtApellidoCrearPac.getText().isEmpty() || txtTelefonoCrearPac.getText().isEmpty() || txtDireccionCrearPac.getText().isEmpty() || txtEmailCrearPac.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Es necesario diligenciar todos los campos", "Datos No Validos", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarListaPac;
    public javax.swing.JButton btnBuscarPaciente;
    public javax.swing.JButton btnCancelarCrearPac;
    public javax.swing.JButton btnCancelarModificarPac;
    public javax.swing.JButton btnGuardarCrearPac;
    public javax.swing.JButton btnGuardarModificarPac;
    public javax.swing.JComboBox<String> cbxCampoaBuscarPac;
    public javax.swing.JComboBox<String> cbxEstadoModificarPac;
    private javax.swing.JPanel cbxEstadoPac;
    public javax.swing.JComboBox<String> cbxModificarBuscarPac;
    public javax.swing.JComboBox<String> cbxTipoDocCrearPac;
    public javax.swing.JComboBox<String> cbxTipoDocModificarPac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu mnArchivoPacientes;
    private javax.swing.JMenuItem mniSalirPacientes;
    private javax.swing.JMenuItem mniVentanaPpalPacientes;
    private javax.swing.JPanel pnBuscarPacientes;
    private javax.swing.JPanel pnCrearPacientes;
    private javax.swing.JPanel pnListarPacientes;
    private javax.swing.JPanel pnModificarDatosPac;
    private javax.swing.JPanel pnModificarPacientes;
    public javax.swing.JTable tblListarPacientes;
    public javax.swing.JTable tblResultadoBuscarPac;
    private javax.swing.JTabbedPane tbpPacientes;
    public javax.swing.JTextField txtApellidoCrearPac;
    public javax.swing.JTextField txtApellidoModificarPac;
    public javax.swing.JTextField txtBuscarPaciente;
    public javax.swing.JTextField txtDireccionCrearPac;
    public javax.swing.JTextField txtDireccionModificarPac;
    public javax.swing.JTextField txtDocumentoCrearPac;
    public javax.swing.JTextField txtDocumentoModificarPac;
    public javax.swing.JTextField txtEmailCrearPac;
    public javax.swing.JTextField txtEmailModificarPac;
    public javax.swing.JTextField txtNombresCrearPac;
    public javax.swing.JTextField txtNombresModificarPac;
    public javax.swing.JTextField txtTelefonoCrearPac;
    public javax.swing.JTextField txtTelefonoModificarPac;
    // End of variables declaration//GEN-END:variables
}
