/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import modelo.conexionMysql;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author INESMARIAO
 */
public class login extends javax.swing.JFrame {
    conexionMysql cc=new conexionMysql();
    Connection con=cc.conexion();
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        // para que la ventana aparezca en el centro de la pantalla
        this.setLocationRelativeTo(null);
        this.setTitle("Login");
    }
    
    public void validarAcceso(){
        int resultado=0;
        try{
            String usuario=txtUsuario.getText();
            String password=String.valueOf(txtPassword.getPassword());
            String sql="select * from usuario where username='" +usuario+ "' and password='" +password+ "'";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            
            if(rs.next()){
                resultado=1;
                
                if(resultado==1){
                    //JOptionPane.showMessageDialog(null,"Bienvenido " + txtUsuario.getText() + " al Sistema de la Clínica de Odontología XYZ");
                    frmPrincipal form=new frmPrincipal();
                    form.setVisible(true);
                    this.dispose();
                }
            }else{
                    JOptionPane.showMessageDialog(null,"Error en el acceso al sistema, vuelve a intentarlo");
                }
        }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Error en el acceso al sistema, vuelve a intentarlo" + e.getMessage());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        imagenLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bthIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Contraseña:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 160, -1));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 160, -1));

        imagenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/locksmith128.png"))); // NOI18N
        jPanel1.add(imagenLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 130, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dientes2.PNG"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 320, 120));

        bthIngresar.setText("Ingresar");
        bthIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(bthIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bthIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthIngresarActionPerformed
        validarAcceso();
    }//GEN-LAST:event_bthIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthIngresar;
    private javax.swing.JLabel imagenLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
